### ISSUE TITLE
Cannot install -r requirements.txt - package versions have conflicting dependencies

### ISSUE THREAD

**Issue by WiktorKwasniak** [IIS-ZPI/ZPI2022_zaoczni_NoProblem#47]
Backend workflow keeps failing on dependency installation step. Please investigate it and create appropriate fix.
_ERROR: Cannot install -r requirements.txt (line 1) and starlette==0.23.1 because these package versions have conflicting dependencies._
[Example logs](https://github.com/IIS-ZPI/ZPI2022_zaoczni_NoProblem/actions/runs/3990362896/jobs/6843904536)

**Comment by 229258** [comment]
Under investigation. Seems like at least one dependency conflict. The newest FastAPI doesn't support the latest versions of Starlette. @Hubertius according to last changes in server do we still use matplotlib library?

**Comment by Hubertius** [comment]
No @229258, it's fine to drop this library from requirements.txt. :)

**Comment by 229258** [comment]
Please, check the PR.
https://github.com/IIS-ZPI/ZPI2022_zaoczni_NoProblem/pull/52

**Comment by 229258** [comment]
I have cancelled PR #52. There was too much of additional changes nonrelated to this issue.
BTW. @Hubertius, why we are using Request from Starlette library instead of the one from main Python libraries?

**Comment by 229258** [comment]
New PR is #53

**Comment by 229258** [comment]
Fixed another issue with python libraries. We had really old version of numpy. I changed it to the newest one (1.24.0). Now, it seems that all libraries have installed succesfully, but job is hanging after the server has started. Possibly it works on first plan instead of in the background and the further instructions (tests) are blocked. @WiktorKwasniak, can you check that?

**Comment by 229258** [comment]
Fix for this issue was introduced in PR #53. Can you retest @WiktorKwasniak
